// Script to seed 2025 tournament points for players
// Run this script once to populate historical data for group balancing

import prisma from '../lib/prisma';

// Real 2025 player points data
const player2025Points = [
  { playerName: 'Joel Meireles', points: 177 },
  { playerName: 'Pedro Santos', points: 208 },
  { playerName: 'Nuno Costa', points: 640 },
  { playerName: 'Tiago Afonso', points: 698 },
  { playerName: 'Bertino', points: 538 },
  { playerName: 'Márcio Teixeira', points: 696 },
  { playerName: 'Guilherme Sousa', points: 607 },
  { playerName: 'Filipe Dias', points: 753 },
  { playerName: 'Rui Vieira', points: 182 },
  { playerName: 'Marcos Garcia', points: 521 },
  { playerName: 'Ricardo Soares', points: 870 },
  { playerName: 'Ângelo Ramos', points: 825 },
  { playerName: 'Vitor Hugo', points: 444 },
  { playerName: 'José Santos', points: 32 },
  { playerName: 'Tomás Marques', points: 28 },
  { playerName: 'Daniel Barros', points: 172 },
  { playerName: 'Valter Martins', points: 224 },
  { playerName: 'António Ribeiro', points: 163 },
  { playerName: 'Rui Bertuzi', points: 651 },
  { playerName: 'António Costa', points: 54 },
  { playerName: 'Rui Moreira', points: 142 },
  { playerName: 'Telmo Carvalho', points: 148 },
  { playerName: 'André Branco', points: 109 },
  { playerName: 'Nuno Macedo', points: 183 },
  { playerName: 'Luís Cadeco', points: 2 },
  { playerName: 'Paulo Ribeiro', points: 35 },
  { playerName: 'João Fernandes', points: 222 },
  { playerName: 'Nuno Machado', points: 125 },
  { playerName: 'Ruben Pinto', points: 68 },
  { playerName: 'Pedro Duarte', points: 120 },
  { playerName: 'Miguel Braga', points: 10 },
  { playerName: 'Vasco Oliveira', points: 42 },
  { playerName: 'Ricardo Gomes', points: 46 },
  { playerName: 'Giorgio Ramondetta', points: 21 },
  { playerName: 'Rui Sampaio', points: 240 },
  { playerName: 'Ricardo Miranda', points: 290 },
  { playerName: 'Leandro Marinho', points: 66 },
  { playerName: 'Marco Leite', points: 600 },
  { playerName: 'Joel Geraldes', points: 306 },
  { playerName: 'Cristiano Cancujo', points: 22 },
  { playerName: 'Miguel Matias', points: 71 },
  { playerName: 'Gustavo Martins', points: 10 },
  { playerName: 'Tiago Monteiro', points: 10 },
  { playerName: 'Cláudio Sá', points: 30 },
  { playerName: 'Nuno Ferreira', points: 417 },
  { playerName: 'Nuno Dias', points: 18 },
  { playerName: 'Miguel Guimarães', points: 35 },
  { playerName: 'Alírio Mota', points: 2 },
  { playerName: 'Miguel Carneiro', points: 19 },
  { playerName: 'Miguel Caldeira', points: 63 },
  { playerName: 'Jorge Guimarães', points: 3 },
  { playerName: 'Hugo Landolt', points: 80 },
  { playerName: 'João Pedro Fonseca', points: 10 },
  { playerName: 'Bruno Oliveira', points: 160 },
  { playerName: 'Tito Coelho', points: 14 },
  { playerName: 'Ricardo Silva', points: 91 },
  { playerName: 'Mateus Morais', points: 5 },
  { playerName: 'Rui Conceição', points: 51 },
  { playerName: 'Pedro Manso', points: 9 },
  { playerName: 'Ruben Moreira', points: 9 },
  { playerName: 'João Alves', points: 17 },
  { playerName: 'Tiago Macieira', points: 32 },
  { playerName: 'Paulo Costa', points: 67 },
  { playerName: 'Diogo Oliveira', points: 10 },
  { playerName: 'Miguel Simões', points: 18 },
  { playerName: 'Francisco Nogueira', points: 4 },
  { playerName: 'João Carvalho', points: 20 },
  { playerName: 'André Cardoso', points: 10 },
  { playerName: 'Miguel Oliveira', points: 642 },
  { playerName: 'Dinis Azevedo', points: 24 },
  { playerName: 'Pedro Pereira', points: 36 },
  { playerName: 'Ricardo Martins', points: 15 },
  { playerName: 'Ricardo Couto Silva', points: 5 },
  { playerName: 'Abílio Monteiro', points: 16 },
  { playerName: 'Júlio Mejia', points: 17 },
  { playerName: 'Pedro Bezelga', points: 325 },
  { playerName: 'Franklin Salas', points: 178 },
  { playerName: 'João Saraiva', points: 245 },
  { playerName: 'Francisco Pinto', points: 14 },
  { playerName: 'Diogo Pimenta', points: 14 },
  { playerName: 'Luís F Sousa', points: 3 },
  { playerName: 'Eduardo Salgado', points: 2 },
  { playerName: 'Luís Faria', points: 18 },
  { playerName: 'Pedro Leite', points: 118 },
  { playerName: 'Daniel Pereira', points: 51 },
  { playerName: 'Paulo Miranda', points: 12 },
  { playerName: 'Eduardo Pintado', points: 1 },
  { playerName: 'Henrique Fernandes', points: 8 },
  { playerName: 'Ricardo Vareiro', points: 78 },
  { playerName: 'João Redondo', points: 91 },
  { playerName: 'Martim Amorim', points: 45 },
  { playerName: 'António Gonçalves Cardoso', points: 93 },
  { playerName: 'Fábio Almeida', points: 26 },
  { playerName: 'Tomás Busto', points: 6 },
  { playerName: 'Miguel Cruz', points: 4 },
  { playerName: 'Fábio Rocha', points: 264 },
  { playerName: 'Francisco Marques', points: 22 },
  { playerName: 'João Coelho', points: 3 },
  { playerName: 'Mateus Carvalho', points: 26 },
  { playerName: 'Nuno G Gonçalves', points: 14 },
  { playerName: 'Paulo Carvalho', points: 13 },
  { playerName: 'Michael Fernandes', points: 6 },
  { playerName: 'Rafael Afonso', points: 65 },
  { playerName: 'Tiago Andrade', points: 5 },
  { playerName: 'Ronny Miller', points: 15 },
  { playerName: 'Ivo Ferreira', points: 45 },
  { playerName: 'Álvaro Pinto', points: 5 },
  { playerName: 'Fernando Mota', points: 69 },
  { playerName: 'Fábio Guimarães', points: 6 },
  { playerName: 'Domi', points: 52 },
  { playerName: 'Daniel Pais', points: 228 },
  { playerName: 'Rui Dias', points: 4 },
  { playerName: 'David Mestre', points: 197 },
  { playerName: 'Nuno Azevedo', points: 136 },
  { playerName: 'Diogo Costa', points: 116 },
  { playerName: 'Gonçalo Martins', points: 62 },
  { playerName: 'Maciel Carvalho', points: 54 },
  { playerName: 'Ricardo Moreira', points: 17 },
  { playerName: 'Leandro Filipe Silva', points: 14 },
  { playerName: 'Paulo Damas', points: 1 },
  { playerName: 'Paulo Leitão', points: 64 },
  { playerName: 'Tiago Pimentel', points: 146 },
  { playerName: 'Filipe Castro', points: 16 },
  { playerName: 'Ricardo Sousa', points: 7 },
  { playerName: 'Miguel Barbosa', points: 31 },
  { playerName: 'Nuno Pires', points: 13 },
  { playerName: 'Jorge Garcia', points: 19 },
  { playerName: 'Zé Luís Silva', points: 34 },
  { playerName: 'António Nunes', points: 23 },
  { playerName: 'Júnior Oliveira', points: 3 },
  { playerName: 'Pedro Monteiro', points: 30 },
  { playerName: 'Nuno Dionísio', points: 6 },
  { playerName: 'Fernando Ferreira', points: 1 },
  { playerName: 'Paulo Matias', points: 77 },
  { playerName: 'Emily Jacome', points: 1 },
  { playerName: 'Carlos Dias', points: 14 },
  { playerName: 'Alberto Silva', points: 13 },
  { playerName: 'Miguel Mendes', points: 20 },
  { playerName: 'Pedro Maia', points: 118 },
  { playerName: 'Ricardo Crespo', points: 102 },
  { playerName: 'Gonçalo Costa', points: 136 },
  { playerName: 'Silvio Monteiro', points: 1 },
  { playerName: 'Tiago Ribeiro', points: 41 },
  { playerName: 'Dinis Sousa', points: 44 },
  { playerName: 'Tiago Almeida', points: 44 },
  { playerName: 'João Ferro', points: 35 },
  { playerName: 'Paulino', points: 31 },
  { playerName: 'Diogo Freitas', points: 4 },
  { playerName: 'João Rafael', points: 12 },
  { playerName: 'António Cardoso', points: 3 },
  { playerName: 'Hugo Ferreira', points: 8 },
  { playerName: 'Nacho Gallo', points: 51 },
  { playerName: 'Rui Moreira Silva', points: 25 },
  { playerName: 'Leandro Gonçalves', points: 4 },
  { playerName: 'João Correia', points: 86 },
  { playerName: 'José Magro', points: 59 },
  { playerName: 'Marco Mesquita', points: 9 },
  { playerName: 'Rodrigo Maganinho', points: 23 },
  { playerName: 'Ricardo Vieira Macedo', points: 1 },
  { playerName: 'Pedro Seabra', points: 156 },
  { playerName: 'Pedro Rosa', points: 5 },
  { playerName: 'Bernardo Ferro', points: 71 },
  { playerName: 'Ricardo Santos', points: 14 },
  { playerName: 'Bruno Osório', points: 8 },
  { playerName: 'Pedro Barral', points: 8 },
  { playerName: 'Hugo Carvalho', points: 7 },
  { playerName: 'Adriano Lopes', points: 18 },
  { playerName: 'Diogo Ribeiro', points: 44 },
  { playerName: 'Nuno Martins', points: 3 },
  { playerName: 'Hugo Guedes', points: 5 },
  { playerName: 'Mário Negrão', points: 73 },
  { playerName: 'Vasco Barbosa', points: 19 },
  { playerName: 'João Costa', points: 1 },
  { playerName: 'Manuel Vieira', points: 5 },
  { playerName: 'João Bernardo', points: 22 },
  { playerName: 'Paulo Sousa', points: 23 },
  { playerName: 'João Oliveira', points: 15 },
  { playerName: 'Hugo Torres', points: 25 },
  { playerName: 'Vitor Silva', points: 3 },
  { playerName: 'Bruno Ramalho', points: 19 },
  { playerName: 'Leandro Gomes', points: 89 },
  { playerName: 'Jay Jesus', points: 79 },
  { playerName: 'Diogo Nunes', points: 13 },
  { playerName: 'Jaqueline Andrade', points: 4 },
  { playerName: 'Pedro Carvalho', points: 21 },
  { playerName: 'Tiago Manso', points: 43 },
  { playerName: 'Paulo Almeida', points: 1 },
  { playerName: 'Pedro Mota', points: 6 },
  { playerName: 'Ana Manso', points: 7 },
  { playerName: 'Daniel Fontes', points: 9 },
  { playerName: 'Luís Braga', points: 10 },
  { playerName: 'Diogo Torres', points: 10 },
  { playerName: 'Torcato Monteiro', points: 17 },
  { playerName: 'Miguel Neto', points: 32 },
  { playerName: 'José Sousa', points: 17 },
  { playerName: 'João Ferreira', points: 17 },
  { playerName: 'Joaquim Monteiro', points: 4 },
  { playerName: 'André Coelho', points: 1 },
  { playerName: 'Samuel Marques', points: 1 },
  { playerName: 'Rita Costa', points: 3 },
  { playerName: 'Luís Costa Pereira', points: 5 },
  { playerName: 'Diogo Pais', points: 6 },
  { playerName: 'Alberto Amorim', points: 8 },
  { playerName: 'Ricardo Ribeiro', points: 5 },
  { playerName: 'Joel Santos', points: 2 },
  { playerName: 'Tiago Ferraz', points: 2 },
  { playerName: 'João Elias', points: 10 },
  { playerName: 'Luís Gomes', points: 10 },
  { playerName: 'Henrique Morais', points: 20 },
  { playerName: 'Tomás Menéres', points: 16 },
  { playerName: 'Gustavo Melo', points: 11 },
  { playerName: 'Bessa', points: 98 },
  { playerName: 'Pedro Cunha', points: 21 },
  { playerName: 'Nuno Cordeiro', points: 14 },
  { playerName: 'Vasco Silva', points: 33 },
  { playerName: 'Eduardo Jesus', points: 21 },
  { playerName: 'Ivan Ortega', points: 86 },
  { playerName: 'Pol Jean-Mairet', points: 2 },
  { playerName: 'Francisco Campos', points: 7 },
  { playerName: 'João Barros', points: 7 },
  { playerName: 'Diogo Neves', points: 2 },
  { playerName: 'Rui Franco', points: 5 },
  { playerName: 'Pedro Marques', points: 10 },
  { playerName: 'Rui Baptista', points: 12 },
  { playerName: 'Jorge Melo', points: 3 },
  { playerName: 'João Paupério', points: 15 },
  { playerName: 'Gonçalo Lopes', points: 1 },
  { playerName: 'Pedro Piçarra', points: 6 },
  { playerName: 'Rui Santos', points: 3 },
  { playerName: 'Francisco Furtado', points: 10 },
  { playerName: 'Joel Ferreira', points: 1 },
  { playerName: 'Tom Ozkavaf', points: 4 },
  { playerName: 'Carlos Teixeira', points: 21 },
  { playerName: 'André Ferreira', points: 25 },
  { playerName: 'Igor Araújo', points: 6 },
  { playerName: 'Pedro Sá Couto', points: 1 },
  { playerName: 'José Silva', points: 1 },
  { playerName: 'Manuel Maia', points: 22 },
  { playerName: 'Hélio Soares', points: 3 },
  { playerName: 'João Vasco Pinto', points: 5 },
  { playerName: 'Pedro Santos 2.0', points: 18 },
  { playerName: 'Raquel Begonha', points: 21 },
  { playerName: 'Luís Valente', points: 3 },
  { playerName: 'Pedro Moreira 2', points: 11 },
  { playerName: 'André Teixeira', points: 10 },
  { playerName: 'Ricardo Oliveira', points: 7 },
  { playerName: 'Martim Ferreira', points: 7 },
  { playerName: 'João Correia 2', points: 6 },
  { playerName: 'Pedro Gomes', points: 29 },
  { playerName: 'Schadia Castillo', points: 23 },
  { playerName: 'Raquel Povoas', points: 20 },
  { playerName: 'Vasco Costa', points: 3 },
  { playerName: 'Nuno Rodrigues', points: 48 },
  { playerName: 'César Carvalho', points: 40 },
  { playerName: 'Quim Ferraz', points: 19 },
  { playerName: 'Tiago Silva', points: 157 },
  { playerName: 'Eduardo Correia', points: 19 },
  { playerName: 'Tomás Bessa', points: 18 },
  { playerName: 'Ricardo Ramos', points: 65 },
  { playerName: 'Damian', points: 34 },
  { playerName: 'Filipe Duarte', points: 13 },
  { playerName: 'Francisco Ramos', points: 18 },
  { playerName: 'Silvério Ramos', points: 16 },
  { playerName: 'Pedro Mendes', points: 2 },
  { playerName: 'Francisco Peixoto', points: 4 },
  { playerName: 'Gonçalo Machado', points: 46 },
  { playerName: 'Miguel Aguiar', points: 26 },
  { playerName: 'Rúben Silva', points: 36 },
  { playerName: 'Francisco Ferreira', points: 14 },
  { playerName: 'João Maia', points: 14 },
  { playerName: 'Ruben Pereira', points: 10 },
  { playerName: 'Ricardo Arcipreste', points: 1 },
  { playerName: 'Hugo Tavares', points: 12 },
  { playerName: 'Celestino Leocádio', points: 6 },
  { playerName: 'Hugo Lima', points: 11 },
  { playerName: 'João Carido', points: 57 },
  { playerName: 'Guilherme Soares', points: 23 },
  { playerName: 'Israel Alves', points: 10 },
  { playerName: 'Tiago Torre', points: 5 },
  { playerName: 'Joel Alegria', points: 4 },
  { playerName: 'João Nakamura', points: 7 },
  { playerName: 'João Azevedo', points: 7 },
  { playerName: 'Francisco Matos', points: 3 },
  { playerName: 'Miguel Pato', points: 53 },
  { playerName: 'Vitor Fernandes', points: 32 },
  { playerName: 'Pedro Tavares', points: 31 },
  { playerName: 'Rafael Cavalheiro', points: 5 },
  { playerName: 'André Rodrigues', points: 1 },
  { playerName: 'Nuno Praça', points: 11 },
  { playerName: 'André Salazar', points: 3 },
  { playerName: 'Pedro Frias', points: 19 },
  { playerName: 'Ivo Tavares', points: 12 },
  { playerName: 'Serafim Santos', points: 1 },
  { playerName: 'Ricardo Pimentel', points: 8 },
  { playerName: 'Pedro Moreira', points: 9 },
  { playerName: 'José Domingues', points: 4 },
  { playerName: 'Francisco Lopes', points: 5 },
  { playerName: 'Gonçalo Freitas', points: 5 },
  { playerName: 'Marco Poço', points: 14 },
  { playerName: 'Hugo Cardoso', points: 18 },
  { playerName: 'Gonçalo Ferro', points: 14 },
  { playerName: 'Fábio Vilas Boas', points: 12 },
  { playerName: 'Ricardo Pereira', points: 17 },
  { playerName: 'Nuno Cardoso', points: 17 },
  { playerName: 'Tiago Somensi', points: 6 },
  { playerName: 'Rui Madureira', points: 6 },
  { playerName: 'Vasco Ramos', points: 8 },
  { playerName: 'Guilherme Carvalho', points: 5 },
  { playerName: 'João Menezes', points: 4 },
  { playerName: 'Sérgio Oliveira', points: 26 },
  { playerName: 'Miguel Ribeiro', points: 16 },
  { playerName: 'Carlos Monterroso', points: 23 },
  { playerName: 'Gabriel Ribeiro', points: 26 },
  { playerName: 'António Rodrigues', points: 7 },
  { playerName: 'Martim Flower', points: 14 },
  { playerName: 'Emanuel Santos', points: 6 },
  { playerName: 'Vasco Rodas', points: 10 },
  { playerName: 'Bruno Teixeira', points: 6 },
  { playerName: 'Domingos Ribeiro', points: 1 },
  { playerName: 'Nuno Brito', points: 23 },
  { playerName: 'Cristiano Aguiar', points: 23 },
  { playerName: 'Paulo Ferreira', points: 4 },
  { playerName: 'João Dias', points: 10 },
  { playerName: 'Luís Silva', points: 1 },
  { playerName: 'Tó Bujardas', points: 23 },
  { playerName: 'André Maia', points: 3 },
  { playerName: 'Nuno Silva', points: 21 },
  { playerName: 'Ricardo Silva 2', points: 1 },
  { playerName: 'Hugo Almeida', points: 26 },
  { playerName: 'Pedro Sá', points: 3 },
  { playerName: 'João Sousa', points: 16 },
  { playerName: 'Rodrigo Costa', points: 16 },
  { playerName: 'Tiago Mendes', points: 5 },
  { playerName: 'Filipe Andrade', points: 5 },
];

async function seed2025Points() {
  console.log('Starting to seed 2025 points...');

  // Get or create a "dummy" tournament for historical points
  let historicalTournament = await prisma.tournament.findFirst({
    where: { name: '[HISTORICAL] 2025 Season Points' },
  });

  if (!historicalTournament) {
    // Find first user to assign the tournament to
    const firstUser = await prisma.user.findFirst();
    if (!firstUser) {
      console.error('No users found. Please create a user first.');
      return;
    }

    historicalTournament = await prisma.tournament.create({
      data: {
        userId: firstUser.id,
        name: '[HISTORICAL] 2025 Season Points',
        type: 'ROUND_ROBIN',
        category: 'OPEN_250',
        status: 'FINISHED',
        maxPhases: 1,
        currentPhase: 1,
        createdAt: new Date('2025-01-15'),
      },
    });
    console.log('Created historical tournament for 2025 points');
  }

  let successCount = 0;
  let errorCount = 0;

  for (const { playerName, points } of player2025Points) {
    try {
      // Find player by name
      const player = await prisma.player.findFirst({
        where: { name: { contains: playerName, mode: 'insensitive' } },
      });

      if (!player) {
        console.warn(`⚠️  Player not found: ${playerName}`);
        errorCount++;
        continue;
      }

      // Check if this player already has a 2025 result
      const existing = await prisma.tournamentResult.findFirst({
        where: {
          playerId: player.id,
          tournamentId: historicalTournament.id,
        },
      });

      if (existing) {
        // Update existing
        await prisma.tournamentResult.update({
          where: { id: existing.id },
          data: {
            pointsAwarded: points,
            bonusPoints: 0,
          },
        });
        console.log(`✅ Updated: ${playerName} - ${points} pts`);
      } else {
        // Create new
        await prisma.tournamentResult.create({
          data: {
            tournamentId: historicalTournament.id,
            playerId: player.id,
            finalPosition: 1,
            pointsAwarded: points,
            bonusPoints: 0,
            category: 'OPEN_250',
            createdAt: new Date('2025-01-15'),
          },
        });
        console.log(`✅ Created: ${playerName} - ${points} pts`);
      }

      successCount++;
    } catch (error) {
      console.error(`❌ Error processing ${playerName}:`, error);
      errorCount++;
    }
  }

  console.log('\n=== Summary ===');
  console.log(`✅ Successfully processed: ${successCount}`);
  console.log(`❌ Errors: ${errorCount}`);
  console.log('\nYou can now create tournaments and they will use these 2025 points for group balancing!');
}

seed2025Points()
  .catch((e) => {
    console.error('Fatal error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
